generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Parlamentario
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          parlamentario_Parlamentario
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   Gesti√≥n de Parlamentarios
        display: [=nombre, apellidos, senador_diputado, id_circunscripcion, id_distrito, pacto, partido]
        sort:    [nombre, asc]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
